TASK: Try next ci script interation

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -248,27 +248,49 @@ deploy-test:
         - |
             ssh $SSH_USER@$SSH_SERVER_URL <<-EOF
 
-            set -ex
+            set -e
 
             docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
 
             cd deployments
-            for dir in */; do
-                if [[ "$(basename "$dir")" == "ingress" ]]; then
+            for dir in */
+            do
+                DIR=$(basename $dir)
+
+                if [[ "$DIR" == "ingress" ]]
+                then
                     echo "Skipping ingress directory"
                     continue
                 fi
 
                 cd $dir
-                echo "=== Updating Instance $(basename "$dir") ==="
-                if [[ ! -f ".env" ]]; then
+                echo "=== Updating Instance $DIR to $IMAGE_TAG ==="
+
+                if [[ ! -f ".env" ]]
+                then
                     echo "Missing .env file, SKIPPING!"
-                else
-                    sed -i "s/^IMAGE_TAG='[^']*'/IMAGE_TAG='$IMAGE_TAG'/" .env
-                    docker compose pull
-                    docker compose up -d
+                    continue
                 fi
+
+                if [[ ! -f "docker-compose.yml" ]]
+                then
+                    echo "Missing docker-compose.yaml.. aborting!"
+                    continue
+                fi
+
+                sed -i "s/^IMAGE_TAG='[^']*'/IMAGE_TAG='$IMAGE_TAG'/" .env
+
+                echo "Restarting docker compose setup with new env:"
+                echo " === "
+                cat .env
+                echo " === "
+
+                docker compose pull
+                docker compose up -d
+
                 cd ..
             done
+
+            echo " === Update done === "
 
             EOF
